<div class="article-wrapper container">
  <h1>CHINEASE Ltd</h1>
  <div class="desc">User Registration Terms</div>

  <h2>Introduction</h2>
  <p>Thank you for choosing to apply to CHINEASE, it’s a decision we’re sure you won’t regret. CHINEASE is an employment and relocation service for English language teachers looking to work in China.  We work closely with our partner colleges and universities, our “<b>Institutions</b>”, to find placements for registered users of CHINEASE and act as the middle man to introduce you to such Institutions.  We’ll refer to this process as our “<b>Service</b>” and you can find more information about the Service by visiting our “<b>Website</b>” at www.chinease.co.uk.</p>
  <p>In order to register with CHINEASE and to access our Service you will first need to read and accept this set of registration terms and conditions (our “<b>Terms</b>”).  Unfortunately, if you don’t accept these Terms, you won’t be able to access our Service. </p>
  <p>CHINEASE is owned and operated by CHINEASE Ltd, a limited company registered in England and Wales with company number 11008547 and whose registered office is located 3 Mariners Wharf, Quayside, Newcastle Upon Tyne, United Kingdom, NE1 2BJ.  When we use words like “CHINEASE”, “<b>we</b>”, “<b>us</b>” and “<b>our</b>” in these Terms, it is to CHINEASE Ltd that we refer.  Likewise, when we use words like “<b>you</b>” and “<b>your</b>”, we are referring to you, whom, we hope, will soon be our registered user. </p>
  <p>You may notice throughout that certain phrases and sentences begin or are followed by a single word, highlighted in bold like “<b>This</b>” or like (“<b>This</b>”).  When you see that we’re telling you we want to use this word as we are defining it there throughout these Terms and we’ll make it clear when we use these definitions again by repeating these words with the Seemingly Inappropriate Use Of Capital Letters.</p>
  <p>All of these Terms apply to anyone who wishes to register to use our Service and when you complete your registration by accepting these Terms, there will be a legal contract between you and us. </p>

  <h2>Your Registration</h2>
  <p>You can register directly through our Website and to register we will require, as a minimum, your full name, age, nationality, national language, degree, email and a phone number.  We may also require some additional information to help identify placements suitable for you, such as your available start date and a copy of your CV.  In completing your registration, you confirm that the information you are providing to us during the process is accurate and up-to-date.  </p>
  <p>By completing the registration process you warrant to us that you have read and accepted these Terms. It is important that you have read and carefully considered these Terms as upon acceptance you are entering into a contract with us and that contract is based upon them.  Don’t worry, you don’t *have* to do anything in particular.  If you register and subsequently decide not to accept a placement and make use of our Service, there’s nothing you are required to do (and if you wish, you can have your registration terminated).  But since you are entering into a contract with us, it would be sensible to have a careful read of these Terms just to make sure you are aware of your position.</p>
  <p>You’ll always be able to find a copy of these Terms on the Website, but you might want to print off a copy for your records.  If you do, please bear in mind that the Terms might change in the future, especially since we may add functionality to our Website and the Service over time.  We may change these Terms and if we do so, we will, of course, contact you to let you know that the Terms are to change, what those changes are and when the changes will come into effect.  If you continue to use the Website and our Service after that, you will do so having accepted the new version of the Terms.</p>

  <h2>You</h2>
  <p>We mentioned above the minimum information that you need to provide us in order for your registration to be effective.  Of course, that information alone will be enough to identify you personally and so for that reason, it is protected under the Data Protection Act 1998, the forthcoming European Union General Data Protection Regulations and the equivalent laws in your jurisdiction if you’re not living in the EU.  You may want to supplement your profile with further information about yourself and the information you post may reveal more about yourself.  We will handle that information in accordance with our Privacy Policy, which forms part of these Terms and thereby, our contract with you.  We must be able to identify you as an individual from the information submitted when you register and to that extent, you confirm that your profile information is accurate and that you will keep it up to date.</p>
  <p>Our contract with you is subject to the exclusive jurisdiction of English courts and is governed by English law.  Because of the way English law works, children are not capable of entering into contracts.  Consequently, to register you must be at least 18 years of age. </p>
  <p>Assuming then that you are over 18 and are capable of entering into contracts that are legally binding upon you, your registration on these Terms gives rise to a binding contract between both you and us and those that may later inherit the benefit of the contract that we have formed.  You may not transfer or sell your rights under this contract to anybody else, nor may you use it as security for anything.  The nature of running a Service like CHINEASE means that we may, for whatever reason, have to ‘assign’ the contract that we’ve formed with you to another business. This may be, for example, as part of a restructure or if we are acquired by another company, but we will let you know in advance of any such ‘assignment’.</p>
  <p>You can terminate your registration at any time.  There is more about this in the Privacy Policy so please follow the instructions there.</p>

  <h2>Us</h2>
  <p>At any given time, we reckon we have a pretty good idea as to how well the functionality we’ve provided is working.  We’re working on new features all the time and occasionally, we may want to replace older features with new, better ones.  It is inevitable that every now and again, we will provide features or functionality that seemed like a really good idea at the time but which, for whatever reason, don’t really catch on with our users and the clients we support.  So when this happens, we reserve the right under these Terms to add or remove functionality and features.  We will do our best to give you some advance notice of this but from time to time, it might not be possible.  For example, if something breaks and it is complicated to fix and not sufficiently popular to warrant dropping everything to fix, we may decide to withdraw it immediately.  That withdrawal may be temporary or it may be that we withdraw it permanently, and we reserve the right to decide what’s best in the circumstances.  We make no warranties to you that use of the Website or our Service will be uninterrupted or error free.</p>
  <p>It might be that new functionality requires changes or additions to these Terms or the Privacy Policy, so when we launch new features, you might want to check to see whether we’ve made any changes to either.</p>
  <p>Consumers enjoy protection under a variety of laws in different jurisdictions around the world and if you are acting as a consumer in registering to use our Website, nothing in these Terms is intended to undermine your protection either in England or wherever you happen to be when you access the Website.  In English law, it would be unlawful for us to attempt to exclude or limit liability for personal injury or death arising from our negligence, or for any loss you suffer as a result of our fraud. The same applies to any statement we make fraudulently intending you to rely on it in entering into this contract with us.  It’s pretty difficult to see how your use of our Website or our Services contained within could result in anybody suffering any kind of physical harm, but we just need to be clear about these things.</p>
  <p>Bearing in mind always the exceptions we have mentioned in the previous paragraph, there are certain types of liability that we are permitted by law to limit or exclude and, accordingly, WE WILL NOT BE LIABLE TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT OR CONSEQUENTIAL LOSS, DAMAGE OR EXPENSE (INCLUDING LOSS OF PROFITS, DATA, BUSINESS OR GOODWILL) THAT YOU MIGHT SUFFER AS A RESULT OF USING THE WEBSITE OR OUR SERVICE, HOWEVER THAT LOSS DAMAGE OR EXPENSE MIGHT ARISE. </p>
  <p>In addition, WE WILL NOT BE LIABLE OR RESPONSIBLE FOR ANY FAILURE TO PERFORM OR FOR THE DELAY IN THE PERFORMANCE OF ANY OF OUR OBLIGATIONS UNDER THESE TERMS THAT IS CAUSED BY EVENTS THAT ARE BEYOND OUR REASONABLE CONTROL. </p>
  <p>You also need to be aware that viruses can be transmitted via websites and apps, not just email.  If you want to make sure that your systems are safe from infection, you should run suitable security software because WE HEREBY EXCLUDE LIABILITY FOR ANY VIRUS INFECTION OR OTHER HARM CAUSED TO YOUR SYSTEMS THROUGH YOUR USE OF THE WEBSITE, ANY CONTENT DOWNLOADED VIA THE WEBSITE OR WHEN FOLLOWING ANY LINKS TO WEBSITES RUN BY OTHER PEOPLE.</p>
  <p>If we happen to make a statement that turns out to be untrue (whether orally or in writing) prior to your registration, then, unless that statement was made fraudulently by us, we will only be liable to you should that untrue statement result in us breaching these Terms.  If it does not, the untrue statement has no impact on our relationship with you save insofar as it may impact on your legal rights as a consumer. </p>
  <p>These limitations and exclusions of liability will survive the termination of your registration (which, in turn, would terminate our contract with you).</p>
  <p>Our Service is designed only to facilitate introductions and we will have no involvement in any contract that you may have with one of our Institutions.  Any contractual issues between yourself and an Institution will in no way involve CHINEASE and any contractual disputes should be dealt with directly between the parties.  Although we endeavour to check the information and details of each of our Institutions when they register with us, we do not guarantee this, nor will we be liable in any way for their actions and for any potential loss of profit or damage to your reputation caused by the action of an Institution.</p>
  <p>There may come occasions where we choose not to insist on your total compliance with your obligations under these Terms or that, where you’ve breached the Terms, we don’t make use of our rights to take action against you.  This does NOT mean, however, that we are waiving those rights.  We can take action against you later if we so choose, and at any time during the lifetime of your registration (or indeed, where necessary, at any time after the termination of your registration), we can return to the issue and insist upon your compliance.</p>

  <h2>Our Website and its “Intellectual Property”</h2>
  <p>If you didn’t already know, intellectual property is the term used to describe things that can be owned but which are not physical in nature.  The owner of intellectual property doesn’t own something that is tangible but instead has the right to control how that intangible thing is used, hence the term “<b>Intellectual Property Rights</b>”.  Trade marks, patents and copyright are well-known and commonplace forms of intellectual property, but there are lots more besides. If you use somebody else’s Intellectual Property Rights without their permission (which is often called a “<b>licence</b>”), you’ve “<b>infringed</b>” their rights.</p>
  <p>We own all of the framework and content that makes up our Website.  That includes all the copyright, the code, the look and feel, the trade marks and graphics. You can use all of that when browsing the Website or viewing our job offerings and Institutions in accordance with these Terms, but absolutely no more than that.  Our logo is a registered trademark and even the copyright in these Terms and the other legal documentation you see on the website is owned by our lawyers and licensed to us for this purpose.  Were we to use your things without asking, you would be most unimpressed.  So please don’t try to use any of the intellectual property that we provide for purposes that are not intended or envisaged by these Terms and in particular, don’t attempt to associate yourself with us or claim any form of endorsement from us because that is just not on.  If you’d like to make use of any of our images or the content from our Website then we may allow you to do so at our complete discretion, to make a request to do so please contact <a href="mailto:info@chinease.co.uk">info@chinease.co.uk</a></p>

  <h2>This Contract</h2>
  <p>From time to time, we will give you information relating to your use of the Service.  This might be information about new functionality or old functionality that we are going to withdraw.  It might be to let you know that we have made changes to these Terms or the Privacy Policy.  We will display this information on the Website and we may also send an email to the address you have given us when registering (which is why we need you to keep that email address up-to-date).  English law requires that certain information that we might have to pass to you has to be in writing, so you accept that any information we provide to you electronically is indeed ‘written’ for this purpose.</p>
  <p>If, for some reason, you need to communicate with us for contractual purposes, you can do this by email addressed to <a href="mailto:info@chinease.co.uk">info@chinease.co.uk/</a> but if you really feel the need, you can send us a letter by post, sent to the address provided at the beginning of these Terms.</p>
  <p>Information that we send to you or you send to us for contractual reasons we’ll call “<b>Notices</b>” for the purposes of these Terms.  There may be times when we all need to know when such a Notice was received.  To make things easy, those Notices will be deemed to be received as follows.  A Notice sent by us to you via a notification sent to your account via the website or an email sent by you to us or us to you, will be regarded as having been received the day AFTER it is sent, just to give everyone a reasonable chance to pick it up.  If a Notice is sent in either direction by letter, that Notice will be regarded as having been received (assuming that it was properly stamped and sent by first class mail) three days AFTER the day on which it was sent, or in the case of a letter sent from overseas by airmail, ten days AFTER the day on which it was sent.</p>
  <p>It might just be that at some point in the future, a court or some other authority has cause to review these Terms and in so doing, rules that some or other part of them is invalid, unlawful or unenforceable.  Obviously, that could cause a bit of a problem, certainly for us and possibly also for you.  So, in the very unlikely event that something like that happens, there will be two consequences.  First, everybody accepts that the rest of the Terms will remain in place between us and that the contract will survive intact with the problematic element removed.  Second, the authority or court taking action may compose a replacement for the stricken terms that do as good a job as reasonably possible as the job previously done by the terms removed or, where the authority or court taking action declines to do so, you agree that we may replace those terms ourselves with something else that complies with the ruling.</p>
  <p>Everything relevant to our contractual relationship with you is set out either in these Terms or in the Privacy Policy.  We have no earlier contractual arrangement or understanding with you or any sort.  If you are acting as the representative of a business, your user account may be linked to that business but if we have a commercial relationship with that business, our contract under these Terms with you stands entirely separately from that.  If there is anything that you seek to rely on in creating your registration, please disregard it right now, because in submitting your registration and accepting these Terms, you must acknowledge that in registering to use our Website, you haven’t relied upon any statement made or promise given by us, whether stated plainly or implied from our conduct UNLESS that representation or statement is repeated either in these Terms or in the Privacy Policy.  We have to have this rule because (1) we need some certainty about our relationship with you, and (2) because imagine having thousands of users and customers and having different, potentially undefined contracts with each: it just wouldn’t work.</p>
  <p>In England, there is a law that gives third parties (that is, people who are not ‘party’ to a contract) certain rights to enforce terms that are intended to benefit them.  This is called the Contracts (Rights of Third Parties) Act 1999 and any right of a third party to take action under this law is excluded.  There may be situations where third parties can take action and where we are not permitted to exclude that possibility, such third party rights remain, so you might want to bear that in mind.</p>
  <p>This concludes these Terms and as soon as you completed your registration through the Website, you will have a binding contract with us. </p>
</div>
